apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
    - name: Docker Hub
      prefix: docker.io
      api_url: https://registry-1.dcpker.io
      credentials: pullsecret:argocd/dockerhub-secret
      defaults: library
      default: true